language: ruby
sudo: required
rvm:
  - 2.1.9
  - 2.3.1

notifications:
  email:
   - raphael.pinson@camptocamp.com
env:
  # Most common LTS Puppet Version
  - PUPPET=4.7 RUBY_AUGEAS=0.5 FORGE_PUBLISH=true
  # Current LTS Puppet Version
  - PUPPET=4.10 RUBY_AUGEAS=0.5

matrix:
  fast_finish: true

install:
  - "travis_retry ./.travis.sh"
script:
  - AUGEAS_LENS_LIB=lib/augeas/lenses:augeas/lenses bundle exec rake
  # Do not include the augeas/ directory in the deployed module
  - rm -rf augeas/
deploy:
  provider: puppetforge
  user: herculesteam
  password:
    secure: "AMqmhJcmD+R8cYvSY9rz2VAb8KDgxmnUO+hZb4HvKpM5Auf9oFibVpRWwwSerN75fFiiL8jn5Zwj5HhmyWr+lWr/x4wsHoQAGwJCoXTE40E+6Ick3DEi8rbvBYJIuBPrGcxW3PxH11uIAy27DBJ21Mp/OzIhKpTmVFv7sPrYr+c="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.1.9
    condition: "$FORGE_PUBLISH = true"
