language: ruby
sudo: required
rvm:
  - 2.1.9
notifications:
  email:
   - raphael.pinson@camptocamp.com
env:
  # Most common LTS Puppet Version
  - PUPPET=4.7 RUBY_AUGEAS=0.5 FORGE_PUBLISH=true
  # Current LTS Puppet Version
  - PUPPET=4.10 RUBY_AUGEAS=0.5


matrix:
  fast_finish: true
  exclude:
# base exclude
    # No support for Ruby 2.0 before Puppet 3.2.0 and ruby-augeas 0.5
    - rvm: 2.1.9
      env: PUPPET=3.0.0 RUBY_AUGEAS=0.3.0
    - rvm: 2.1.9
      env: PUPPET=3.2.0 RUBY_AUGEAS=0.3.0
    - rvm: 2.1.9
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0
    - rvm: 2.1.9
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
    - rvm: 2.1.9
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
    - rvm: 2.1.9
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
    - rvm: 2.1.9
      env: PUPPET=3.0.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
    - rvm: 2.1.9
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
    - rvm: 2.1.9
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0 LENSES=HEAD
    - rvm: 2.1.9
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0 LENSES=HEAD
    # No support for Ruby 1.8 in Puppet 4

install:
  - "travis_retry ./.travis.sh"
script:
  - AUGEAS_LENS_LIB=lib/augeas/lenses:augeas/lenses bundle exec rake
  # Do not include the augeas/ directory in the deployed module
  - rm -rf augeas/
deploy:
  provider: puppetforge
  user: herculesteam
  password:
    secure: "AMqmhJcmD+R8cYvSY9rz2VAb8KDgxmnUO+hZb4HvKpM5Auf9oFibVpRWwwSerN75fFiiL8jn5Zwj5HhmyWr+lWr/x4wsHoQAGwJCoXTE40E+6Ick3DEi8rbvBYJIuBPrGcxW3PxH11uIAy27DBJ21Mp/OzIhKpTmVFv7sPrYr+c="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.1.9
    condition: "$FORGE_PUBLISH = true"
