HOSTS:
  server:
    roles:
      - server
      - default
      - master
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  centos-client:
    roles:
      - agent
      - client
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
# Needs testing
#  ubuntu-client:
#    roles:
#      - agent
#      - client
#    platform:   ubuntu-14.04-x86_64
#    box:        ubuntu/trusty64
#    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
  synced_folder: disabled
  ## vb_gui: true
